#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.77.207, Fri Dec  1 10:02:48 2023

#define DB_VERSION_UNIQ_ID "0x6f8034ac"

#endif //_DB_VERSION_H
